name: Kernel Build (OnePlus SM8250)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set Swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git curl wget unzip zip lzop \
            bc bison build-essential \
            ccache device-tree-compiler \
            flex libssl-dev \
            libncurses5-dev libncursesw5-dev \
            make python3 jq

      - name: Cache Clang Toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: kernel_workspace/clang-aosp
          key: clang-r536225

      - name: Download and Extract Clang (if not cached)
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          mkdir -p kernel_workspace/clang-aosp
          wget -O clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r536225.tar.gz
          tar -C kernel_workspace/clang-aosp -zxvf clang.tar.gz

      - name: Cache GCC Toolchain (NDK)
        id: cache-gcc
        uses: actions/cache@v4
        with:
          path: kernel_workspace/gcc-64
          key: ndk-r25c-gcc-toolchain

      - name: Download and Extract GCC (NDK r25c) if not cached
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        run: |
          mkdir -p kernel_workspace
          cd kernel_workspace
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64 gcc-64

      - name: Clone Kernel Source
        run: |
          mkdir -p kernel_workspace
          cd kernel_workspace
          git clone https://github.com/crdroidandroid/android_kernel_oneplus_sm8250 -b 15.0 android-kernel --depth=1

      - name: Patch Kernel with KernelSU and SuSFS
        run: |
          cd kernel_workspace/android-kernel
          curl -LSs https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh | bash -
          curl -LSs https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh | bash -s next-susfs

      - name: Build Kernel
        env:
          ARCH: arm64
          SUBARCH: arm64
          CLANG_TRIPLE: aarch64-linux-gnu-
          CROSS_COMPILE: ${{ github.workspace }}/kernel_workspace/gcc-64/bin/aarch64-linux-android-
          PATH: ${{ github.workspace }}/kernel_workspace/clang-aosp/bin:${{ github.workspace }}/kernel_workspace/gcc-64/bin:/usr/bin:/bin:/usr/sbin:/sbin
        run: |
          cd kernel_workspace/android-kernel
          make O=out clean
          make O=out vendor/kona-perf_defconfig
          make -j$(nproc) O=out

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Kernel-Image-${{ github.sha }}
          path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image
          if-no-files-found: error
