
name: KernelSU and SuSFS Integration

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Integrate KernelSU and SuSFS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/crdroidandroid/android_kernel_oneplus_sm8250 -b 15.0 android-kernel --depth=1

    - name: Integrate KernelSU
      run: |
        cd android-kernel
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: Integrate SuSFS
      run: |
        cd android-kernel
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Build Patched Kernel
      run: |
        cd android-kernel
        export ARCH=arm64
        export SUBARCH=arm64
        make O=out vendor/kona-perf_defconfig
        make -j$(nproc) O=out

    - name: Upload Built Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Patched-Kernel-Image-${GITHUB_SHA}
        path: android-kernel/out/arch/arm64
        /boot/Image
