name: Build Patched Kernel (KernelSU Next + SuSFS)

on:
 workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set 10GB Swap
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git ccache flex bison build-essential \
          libssl-dev bc libncurses5-dev libncursesw5-dev \
          python3 wget unzip zip curl lzop device-tree-compiler

    - name: Prepare Workspace
      run: mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Cache Clang Toolchain
      id: cache-clang
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/kernel_workspace/clang-aosp
        key: clang-r536225

    - name: Download Clang
      if: steps.cache-clang.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir -p clang-aosp
        wget -O clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r536225.tar.gz
        tar -C clang-aosp -zxvf clang.tar.gz

    - name: Cache GCC Toolchain
      id: cache-gcc
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/kernel_workspace/gcc-64
        key: gcc-aarch64-android-12.1.0_r27

    - name: Download GCC
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir -p gcc-64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc-64 -zxvf gcc-aarch64.tar.gz

    - name: Clone Kernel Source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/crdroidandroid/android_kernel_oneplus_sm8250 -b 15.0 android-kernel --depth=1

    - name: Patch Kernel with KernelSU and SuSFS
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel

        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Build Patched Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin:$PATH
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export CROSS_COMPILE=aarch64-linux-android-
        make O=out vendor/kona-perf_defconfig
        make -j$(nproc) O=out

    - name: Upload Built Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Patched-Kernel-Image
        path: kernel_workspace/android-kernel/out/arch/
        arm64/boot/Image
